version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: appsec-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api_db
      MYSQL_USER: appsec
      MYSQL_PASSWORD: appsec123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
